const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
const dotenv = require('dotenv')
const cookieParser = require('cookie-parser')
const authRouter = require('../backend/src/routes/authRouter')
const capsuleRoute = require('../backend/src/routes/capsuleRoute')
require("dotenv").config();

const app = express()
const PORT = process.env.PORT || 5000
app.use(express.json())
app.use(cors())
app.use(cookieParser())
mongoose.connect(process.env.DATABASE_URL)
.then(()=>console.log('MongoDB connected Successfully'))
.catch(err=>console.log('Cannot connect to DB',err))
app.use('/auth',authRouter)
app.use('/capsules',capsuleRoute)
app.listen(PORT,()=>console.log(`Server running on http://localhost:${PORT}`))